package com.example.multimedia.file_upload_api.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

/**
 * Request For Quotation (RFQ).
 *
 * Created by a Purchase Dept user after a PR is APPROVED.
 * Links one PR to one or more vendors who will submit quotations.
 *
 * Status lifecycle: DRAFT → SENT → CLOSED
 */
@Entity
@Table(name = "rfq")
public class Rfq {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "rfq_id")
    private Long rfqId;

    /**
     * Human-readable RFQ number, e.g. RFQ-2026-0001.
     * Generated by the service layer before save.
     */
    @Column(name = "rfq_number", unique = true, nullable = false, length = 50)
    private String rfqNumber;

    /**
     * The purchase requisition this RFQ is based on.
     * Must be in APPROVED status at RFQ creation time.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pr_id", nullable = false)
    private PurchaseRequisition purchaseRequisition;

    /**
     * The Purchase Dept user who created this RFQ.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private UserDetail createdBy;

    /**
     * RFQ status: DRAFT | SENT | CLOSED
     */
    @Column(name = "status", nullable = false, length = 50)
    private String status = "DRAFT";

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Timestamp createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Timestamp updatedAt;

    /**
     * Vendors assigned to this RFQ.
     */
    @OneToMany(mappedBy = "rfq", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<RfqVendor> rfqVendors = new ArrayList<>();

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public Long getRfqId() {
        return rfqId;
    }

    public void setRfqId(Long rfqId) {
        this.rfqId = rfqId;
    }

    public String getRfqNumber() {
        return rfqNumber;
    }

    public void setRfqNumber(String rfqNumber) {
        this.rfqNumber = rfqNumber;
    }

    public PurchaseRequisition getPurchaseRequisition() {
        return purchaseRequisition;
    }

    public void setPurchaseRequisition(PurchaseRequisition purchaseRequisition) {
        this.purchaseRequisition = purchaseRequisition;
    }

    public UserDetail getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(UserDetail createdBy) {
        this.createdBy = createdBy;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<RfqVendor> getRfqVendors() {
        return rfqVendors;
    }

    public void setRfqVendors(List<RfqVendor> rfqVendors) {
        this.rfqVendors = rfqVendors;
    }
}
