-- Rename existing columns and add missing ones to match the 5 SAP report excel headers
-- exactly (see excels/*.xlsx row 5). Only columns confirmed unused by any Java/WorkFlow
-- code (ReportService's report methods are still hardcoded mocks; these entities are
-- otherwise unreferenced) were touched. Columns with no excel counterpart (SAP-integration
-- bookkeeping fields) are left untouched, and new columns are all nullable.

ALTER TABLE vendor_payments
  RENAME COLUMN vendor_code TO vendor_no,
  RENAME COLUMN invoice_reference TO invoice_no,
  RENAME COLUMN sap_reference TO po_number,
  RENAME COLUMN fi_document_number TO sap_invoice_doc_no,
  RENAME COLUMN payment_term TO payment_terms_days,
  RENAME COLUMN tds_deducted TO tds_amount,
  RENAME COLUMN net_paid TO net_amount_payable,
  RENAME COLUMN document_number TO payment_document_no,
  RENAME COLUMN utr_cheque_number TO bank_reference_utr_no,
  RENAME COLUMN overdue_days TO days_overdue,
  RENAME COLUMN vendor_bank_name TO bank_name,
  RENAME COLUMN branch_name TO bank_branch,
  RENAME COLUMN vendor_bank_account TO bank_account_no,
  RENAME COLUMN ifsc_code TO ifsc_swift,
  RENAME COLUMN tds_certificate_number TO tds_certificate_no,
  ADD COLUMN vendor_name VARCHAR(190) NULL,
  ADD COLUMN vendor_gstin VARCHAR(190) NULL,
  ADD COLUMN vendor_pan VARCHAR(190) NULL,
  ADD COLUMN due_date DATE NULL,
  ADD COLUMN net_amount_excl_gst DECIMAL(18,2) NULL,
  ADD COLUMN tax_amount_gst DECIMAL(18,2) NULL,
  ADD COLUMN tds_deducted_pct DECIMAL(6,2) NULL,
  ADD COLUMN amount_paid DECIMAL(18,2) NULL,
  ADD COLUMN balance_outstanding DECIMAL(18,2) NULL,
  ADD COLUMN account_holder_name VARCHAR(190) NULL,
  ADD COLUMN account_type VARCHAR(190) NULL,
  ADD COLUMN remarks VARCHAR(500) NULL;

ALTER TABLE vendor_returns
  RENAME COLUMN material_document TO grn_material_doc_no,
  RENAME COLUMN movement_type TO return_movement_type,
  RENAME COLUMN net_price TO unit_price,
  RENAME COLUMN net_value TO return_value_excl_gst,
  RENAME COLUMN order_unit TO uom,
  RENAME COLUMN plant_code TO plant,
  RENAME COLUMN po_item TO po_line_item,
  RENAME COLUMN purchase_order_number TO original_po_no,
  RENAME COLUMN quantity TO return_quantity,
  RENAME COLUMN status TO return_status,
  RENAME COLUMN supplier_code TO vendor_no,
  RENAME COLUMN supplier_name TO vendor_name,
  ADD COLUMN return_document_no VARCHAR(190) NULL,
  ADD COLUMN return_doc_type VARCHAR(190) NULL,
  ADD COLUMN storage_location VARCHAR(190) NULL,
  ADD COLUMN vendor_gstin VARCHAR(190) NULL,
  ADD COLUMN ref_inbound_delivery_no VARCHAR(190) NULL,
  ADD COLUMN delivery_item VARCHAR(190) NULL,
  ADD COLUMN delivery_date DATE NULL,
  ADD COLUMN vendor_invoice_no VARCHAR(190) NULL,
  ADD COLUMN hsn_sac_code VARCHAR(190) NULL,
  ADD COLUMN batch_no VARCHAR(190) NULL,
  ADD COLUMN delivered_quantity DECIMAL(18,3) NULL,
  ADD COLUMN tax_rate_pct DECIMAL(6,2) NULL,
  ADD COLUMN gst_amount DECIMAL(18,2) NULL,
  ADD COLUMN total_return_value DECIMAL(18,2) NULL,
  ADD COLUMN return_reason VARCHAR(190) NULL,
  ADD COLUMN quality_notification_no VARCHAR(190) NULL,
  ADD COLUMN transporter_lr_no VARCHAR(190) NULL,
  ADD COLUMN dispatch_date_to_vendor DATE NULL,
  ADD COLUMN debit_note_credit_memo_no VARCHAR(190) NULL,
  ADD COLUMN debit_note_date DATE NULL,
  ADD COLUMN remarks VARCHAR(500) NULL;

ALTER TABLE vendor_credit_notes
  RENAME COLUMN amount TO total_credit_amount,
  RENAME COLUMN document_number TO credit_note_no,
  RENAME COLUMN material_description TO description,
  RENAME COLUMN material_document TO sap_credit_memo_doc_no,
  RENAME COLUMN plant_code TO plant,
  RENAME COLUMN po_item TO po_line_item,
  RENAME COLUMN posting_date TO credit_note_date,
  RENAME COLUMN purchase_order_number TO original_po_no,
  RENAME COLUMN quantity TO credit_quantity,
  RENAME COLUMN status TO portal_status,
  RENAME COLUMN unit_of_measure TO uom,
  RENAME COLUMN vendor_code TO vendor_no,
  ADD COLUMN vendor_gstin VARCHAR(190) NULL,
  ADD COLUMN vendor_pan VARCHAR(190) NULL,
  ADD COLUMN credit_note_type VARCHAR(190) NULL,
  ADD COLUMN original_invoice_no VARCHAR(190) NULL,
  ADD COLUMN original_invoice_date DATE NULL,
  ADD COLUMN sap_invoice_doc_no VARCHAR(190) NULL,
  ADD COLUMN return_document_no VARCHAR(190) NULL,
  ADD COLUMN debit_note_no VARCHAR(190) NULL,
  ADD COLUMN debit_note_date DATE NULL,
  ADD COLUMN reason_for_credit_note VARCHAR(190) NULL,
  ADD COLUMN hsn_sac_code VARCHAR(190) NULL,
  ADD COLUMN unit_price DECIMAL(18,2) NULL,
  ADD COLUMN credit_amount_excl_gst DECIMAL(18,2) NULL,
  ADD COLUMN tax_rate_pct DECIMAL(6,2) NULL,
  ADD COLUMN gst_amount DECIMAL(18,2) NULL,
  ADD COLUMN tds_pct DECIMAL(6,2) NULL,
  ADD COLUMN tds_reversal_amount DECIMAL(18,2) NULL,
  ADD COLUMN net_credit_adjustable DECIMAL(18,2) NULL,
  ADD COLUMN adjust_against_invoice_no VARCHAR(190) NULL,
  ADD COLUMN settlement_mode VARCHAR(190) NULL,
  ADD COLUMN account_holder_name VARCHAR(190) NULL,
  ADD COLUMN bank_name VARCHAR(190) NULL,
  ADD COLUMN bank_account_no VARCHAR(190) NULL,
  ADD COLUMN ifsc_swift VARCHAR(190) NULL,
  ADD COLUMN submission_date DATE NULL,
  ADD COLUMN submitted_by_user VARCHAR(190) NULL,
  ADD COLUMN attachment_yn VARCHAR(1) NULL,
  ADD COLUMN remarks VARCHAR(500) NULL;

ALTER TABLE vendor_invoice
  RENAME COLUMN bill_type TO invoice_type,
  RENAME COLUMN gst_number TO vendor_gstin,
  RENAME COLUMN invoice_currency TO currency,
  RENAME COLUMN invoice_due_date TO due_date,
  RENAME COLUMN invoice_number TO invoice_no,
  RENAME COLUMN invoice_total_amount TO line_total_gross,
  RENAME COLUMN payable_amount_inc_gst TO net_amount_payable,
  RENAME COLUMN status TO portal_status,
  RENAME COLUMN subtotal_amount TO line_amount_net,
  RENAME COLUMN tds_rate TO tds_deducted_pct,
  RENAME COLUMN vendor_number TO vendor_no,
  RENAME COLUMN delivery_note_number TO grn_delivery_note_no,
  RENAME COLUMN gst_total_amount TO tax_amount_gst,
  RENAME COLUMN sap_tax_code TO tax_code,
  ADD COLUMN vendor_name VARCHAR(190) NULL,
  ADD COLUMN vendor_pan VARCHAR(190) NULL,
  ADD COLUMN vendor_address VARCHAR(500) NULL,
  ADD COLUMN po_number_ebeln VARCHAR(190) NULL,
  ADD COLUMN place_of_supply VARCHAR(190) NULL,
  ADD COLUMN payment_terms_days VARCHAR(190) NULL,
  ADD COLUMN payment_method VARCHAR(190) NULL,
  ADD COLUMN account_holder_name VARCHAR(190) NULL,
  ADD COLUMN bank_name VARCHAR(190) NULL,
  ADD COLUMN bank_branch VARCHAR(190) NULL,
  ADD COLUMN bank_account_no VARCHAR(190) NULL,
  ADD COLUMN account_type VARCHAR(190) NULL,
  ADD COLUMN ifsc_swift VARCHAR(190) NULL,
  ADD COLUMN submission_date DATE NULL,
  ADD COLUMN submitted_by_user VARCHAR(190) NULL,
  ADD COLUMN attachment_yn VARCHAR(1) NULL;

ALTER TABLE vendor_invoice_item
  RENAME COLUMN item_code TO material_service_code,
  RENAME COLUMN hsn_code TO hsn_sac_code,
  RENAME COLUMN rate TO unit_price,
  RENAME COLUMN basic_amount TO line_amount_net,
  RENAME COLUMN line_total TO line_total_gross,
  ADD COLUMN po_line_item VARCHAR(190) NULL,
  ADD COLUMN uom VARCHAR(190) NULL,
  ADD COLUMN tax_rate_pct DECIMAL(6,2) NULL,
  ADD COLUMN tax_amount_gst DECIMAL(18,2) NULL;

ALTER TABLE current_stock
  RENAME COLUMN plant_code TO plant,
  RENAME COLUMN unit_of_measure TO uom,
  RENAME COLUMN unrestricted_stock TO total_stock_quantity,
  RENAME COLUMN vendor_code TO vendor_no,
  ADD COLUMN vendor_gstin VARCHAR(190) NULL,
  ADD COLUMN hsn_sac_code VARCHAR(190) NULL,
  ADD COLUMN last_supplied_po_no VARCHAR(190) NULL,
  ADD COLUMN last_grn_date DATE NULL,
  ADD COLUMN last_supplied_quantity DECIMAL(18,3) NULL,
  ADD COLUMN remarks VARCHAR(500) NULL;
